### ISSUE TITLE
fast-hadamard-transform not compatible with system GLIBC library version

### ISSUE THREAD

**Issue by YilunKuang** [Dao-AILab/fast-hadamard-transform#3]
Hi, I am trying to use this package but it seems to require GLIBC_2.29. 

```bash
(quip_tokenize) [USER]$ python
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fast_hadamard_transform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/anaconda3/envs/quip_tokenize/lib/python3.10/site-packages/fast_hadamard_transform/__init__.py", line 3, in <module>
    from fast_hadamard_transform.fast_hadamard_transform_interface import hadamard_transform
  File "/home/USER/anaconda3/envs/quip_tokenize/lib/python3.10/site-packages/fast_hadamard_transform/fast_hadamard_transform_interface.py", line 13, in <module>
    import fast_hadamard_transform_cuda
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/USER/anaconda3/envs/quip_tokenize/lib/python3.10/site-packages/fast_hadamard_transform_cuda.cpython-310-x86_64-linux-gnu.so)
```

On my system I only have version 2.26

```bash
(quip_tokenize) [USER]$ ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Do you have any recommendations if I don't have `sudo` access to install a new version of GLIBC? Also, here is my `fast-hadamard-transform` version.

```bash
(quip_tokenize) [USER]$ pip show fast-hadamard-transform
Name: fast-hadamard-transform
Version: 1.0.1
Summary: Fast Hadamard Transform in CUDA, with a PyTorch interface
Home-page: https://github.com/Dao-AILab/fast-hadamard-transform
Author: Tri Dao
Author-email: trid@cs.stanford.edu
License: 
Location: /home/ec2-user/anaconda3/envs/quip_tokenize/lib/python3.10/site-packages
Requires: ninja, packaging, torch
Required-by: 
```

Thank you!

**Comment by YilunKuang** [comment]
solved it with `pip install -e .` instead of the pypi version. Marking this as closed.
