### ISSUE TITLE
Failure during install - "packaging" not found

### ISSUE THREAD

**Issue by nailimixaM** [Dao-AILab/fast-hadamard-transform#4]
Error log:

Collecting fast-hadamard-transform
  Downloading fast_hadamard_transform-1.0.4.post1.tar.gz (6.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-btg1baro/fast-hadamard-transform_f9d0fee24bb546b68ab99dd561c6de4e/setup.py", line 8, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by alugowski** [comment]
Needs `pip install wheel`

**Comment by arashakb** [comment]
I am having the same error. doing ```pip install wheel``` didn't solve the issue.

**Comment by alugowski** [comment]
> I am having the same error. doing `pip install wheel` didn't solve the issue.

It solves the explicit error in this issue:
```
ModuleNotFoundError: No module named 'packaging'
```

That module is installed with `pip install wheel`.

You're right that IIRC there were more missing dependencies. This repo needs a CI as installing on a clean venv will catch such issues.
